// ==========================================
// Author  : If you like content like this, you can join this channel. ðŸ“²
// Contact : https://t.me/jieshuo_materials
// ==========================================

name = "annisapis"
pages_build_output_dir = "." 
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
AUTHOR = "AngelaImut"